### PR TITLE
solution_id save &display

### PR DESCRIPTION
**Pull request by WSbaikaishui**
I find that other explorer has a parameter named solutionID, so I try to add it to your explorer

### CODE REVIEW

**Comment by HarukaMa** [comment]
I should have done this but keep forgetting.

Please add a database migration as well so we don't need to resync from start. Otherwise this will have to wait for the next network. There is a `solution_to_id` function from the rust part and you can use that to calculate all solution IDs for existing solutions.

Also, as this would be the first significant contribution to the project, please review the DCO at https://developercertificate.org/ and state explicitly here that you agree with contributing under that. Commit message signing off is not required here.

**Comment by WSbaikaishui** [comment]
that‘s ok，I will do it later

**Comment by WSbaikaishui** [comment]
Firstly, I have reviewed the Developer Certificate of Origin (DCO) at https://developercertificate.org/ and I explicitly agree to contribute under its terms.
On the second point, I tried using a migration to add solution_id. It works, but it takes a lot of time. Do you have any suggestions to make it work faster?

**Comment by HarukaMa** [comment]
As long as it's faster than resync I'd take that as a win. Looks like there are around 80k solutions, I tried to run the migration locally and it only took less than a minute, and that's perfectly fine for me. 

Thanks for adding this!

**Pull request merged**
